module.exports = {
  users: [
    {
      username: "slimshady",
      fullName: "Max Gibes",
      email: "slim@shady.com",
      password: "supersecret",
      posts: [],
      bio: "Im slim shady yeah im the real shady",
      github: "MGKGOTNOTHINGONME@github",
    },
    {
      username: "Michael-Jordan",
      fullName: "Michael Jordan",
      email: "jordan@nike.com",
      password: "sercretpass",
      posts: [],
      bio: "Buy my shoes",
      github: "Nike>Adidas@github",
    },
    {
      username: "Dwight Likes Bears",
      fullName: "Dwight Schrute",
      email: "office@place.com",
      password: "stuffandthings",
      posts: [],
      bio: "False, Im now a developer",
      github: "Dwight@github",
    },
    {
      username: "Jackson",
      fullName: "Dwight Schrute",
      email: "office@place.com",
      password: "stuffandthings",
      posts: [],
      bio: "False, Im now a developer",
      github: "Dwight@github",
    },
    {
      username: "Tessa",
      fullName: "Tessa Robinson",
      email: "T@gmail.com",
      password: "12345",
      posts: [],
      bio: "False, Im now a developer",
      github: "Dwight@github",
    },
    {
      username: "Bryan",
      fullName: "Dwight Schrute",
      email: "office@place.com",
      password: "12345",
      posts: [],
      bio: "False, Im now a developer",
      github: "Dwight@github",
    },
    {
      username: "Bradley",
      fullName: "Dwight Schrute",
      email: "office@place.com",
      password: "stuffandthings",
      posts: [],
      bio: "False, Im now a developer",
      github: "Dwight@github",
    },
  ],
};
